collections:
  projects:
    output: true
  notes:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "notes"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project-status"