#!/bin/bash

# Check for git
which git >/dev/null
if [ $? -eq 1 ]; then
    echo Please install git
    exit 1
fi

cd ~

# Get the dotfiles
if [ ! -d dotfiles ]; then
    git clone https://github.com/ryan3r/dotfiles.git
fi

# Update/Install the dot files
cd dotfiles
chmod +x update
exec ./update
