#!/bin/bash

# Determine which package manager this system uses
package_manager() {
    for manager in "apt-get"; do
        which $manager >/dev/null
        if [ $? -eq 0 ]; then
            echo $manager
            return
        fi
    done
}

# Print a command and then run it
print_run() {
    echo -e ">> $1"
    eval "$1 >/dev/null"
}

echo "[0/?] Clone dotfiles"

# Check for git
which git >/dev/null
if [ $? -eq 1 ]; then
    if [ $EUID -eq 0 ]; then
        case "$(package_manager)" in
            apt-get)
                print_run "apt-get update"
                print_run "apt-get install -y git"
                ;;
            
            *)
                echo Please install git
                exit 1
                ;;
        esac
    else 
        echo Please install git
        exit 1
    fi
fi

cd ~

# Get the dotfiles
if [ ! -d dotfiles ]; then
    print_run "git clone https://github.com/ryan3r/dotfiles.git"

    if [ $SUDO_USER ]; then
        print_run "chown -R $SUDO_USER:$(id -gn $SUDO_USER) ~/dotfiles"
    fi
fi

# Update/Install the dot files
cd dotfiles
chmod +x update
exec ./update
