#!/bin/bash

echo -e "\033[0;32m[0/-] Cloning dotfiles\033[0;0m"

# Check for git
command -v git >/dev/null || {
	echo "Please install git"
	exit 1
}

cd ~

# Get the dotfiles
if [ ! -d dotfiles ]; then
    echo -e "\033[0;36m>> git clone https://github.com/ryan3r/dotfiles.git
\033[0;0m"
    git clone https://github.com/ryan3r/dotfiles.git
fi

# Update/Install the dot files
cd dotfiles
exec ./bin/update-dotfiles
